apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wordpress.name" . }}
    helm.sh/chart: {{ include "wordpress.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  default.conf: >-
        server {
            listen 80 default_server;
            server_name www.tokentuber.com tokentuber.com; #根据域名更改配置

            large_client_header_buffers 4 16k;     # 读取大型客户端请求头的缓冲区的最大数量和大小
            client_max_body_size 300m;     #设置nginx能处理的最大请求主体大小。
            client_body_buffer_size 128k;  #请求主体的缓冲区大小。

            root /var/www/html;
            index index.php;

            access_log /var/log/nginx/access.log;
            error_log /var/log/nginx/error.log;

            location / {
                try_files $uri $uri/ /index.php?$args;
            }

            location ~ \.php$ {
                try_files $uri =404;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            }
        }


{{ toYaml .Values.db | indent 2 }}
