##############Deployment##############################
kind: Deployment
image:
  tokentubersearch:
    env: prod
    repository: "tokentuber.azurecr.io/tokentubersearch"
    tag: "develop-44132b5a177ad8914e0266979786522f56762bc6"
    pullPolicy: "IfNotPresent"
##############Global_Configurations##################
updateStrategy:
  type: RollingUpdate
tokentubersearch:
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
  podAnnotations:
  terminationGracePeriodSeconds: 10
  env:
    - name: "APP_OPTS"
      value: ""
  envFrom:
  ports:
    - name: dist8082
      containerPort: 8082
      protocol: TCP
  service:
    type: NodePort
    ports:
      - name: dist-8082
        port: 80
        nodePort: 30060
        targetPort: 8082
        protocol: TCP
registrykey: azureregistrykey

env:
  - name: ELASTICSEARCH_HOST
    value: "23.99.120.188"
  - name: ELASTICSEARCH_PORT
    value: "32300"
  - name: ELASTICSEARCH_SCHEMA
    value: http
  - name: ELASTICSEARCH_USERNAME
    value: elastic
  - name: ELASTICSEARCH_PASSWORD
    value: "z5YcyudhjVcgF6JAV7bxz1h7"
  
