apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
  labels:
    app: wordpress
data:
   default.conf: >- 
     server {
     listen 80 default_server;
     server_name internal-dev.tokentuber.com;

     root /var/www/html;
     index index.php;

     access_log /var/log/nginx/access.log;
     error_log /var/log/nginx/error.log;
  
     location / {
         try_files $uri $uri/ /index.php?$args;
     }
 
     location ~ \.php$ {
         try_files $uri =404;
         fastcgi_split_path_info ^(.+\.php)(/.+)$;
         fastcgi_pass 127.0.0.1:9000;
         fastcgi_index index.php;
         include fastcgi_params;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         fastcgi_param PATH_INFO $fastcgi_path_info;
        }
     }
   WORDPRESS_DB_HOST: 10.240.0.4
