apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prod-tokentuber
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  rules:
  - host: www.tokentuber.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
  - host: tokentuber.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
  tls:
  - hosts:
    - www.tokentuber.com
    - tokentuber.com
    secretName: tokentuber-secret    
